"""empty message

Revision ID: 2176ea8461d8
Revises: 5753485a9f00
Create Date: 2014-04-09 16:35:36.270393

"""

# revision identifiers, used by Alembic.
revision = '2176ea8461d8'
down_revision = '5753485a9f00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=64), nullable=False),
    sa.Column('blurb', sa.Unicode(length=144), nullable=False),
    sa.Column('spec', sa.Unicode(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    ### end Alembic commands ###
