"""empty message

Revision ID: 5753485a9f00
Revises: 1510a87bbc01
Create Date: 2014-04-08 12:44:57.706757

"""

# revision identifiers, used by Alembic.
revision = '5753485a9f00'
down_revision = '1510a87bbc01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.Unicode(length=150), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.Unicode(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
